# Generated by Django 2.1.2 on 2018-11-09 13:11

import api.models.logical_model
import api.models.maboss
import api.models.project
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=12)),
                ('format', models.CharField(choices=[('ZGinML', 'ZGinML'), ('MaBoSS', 'MaBoSS'), ('SBML', 'SBML')], default='ZGinML', max_length=10)),
                ('file', models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model)),
                ('bnd_file', models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model)),
                ('cfg_file', models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model)),
            ],
        ),
        migrations.CreateModel(
            name='MaBoSSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=256)),
                ('port', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaBoSSSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=12)),
                ('bnd_file', models.FileField(upload_to=api.models.maboss.path_simulation_model)),
                ('cfg_file', models.FileField(upload_to=api.models.maboss.path_simulation_model)),
                ('fptable', models.TextField(null=True)),
                ('nodes_probtraj', models.TextField(null=True)),
                ('states_probtraj', models.TextField(null=True)),
                ('fixpoints', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Interrupted', 'Interrupted'), ('Running', 'Busy'), ('Finished', 'Ended'), ('Failed', 'Error')], default='Queued', max_length=15)),
                ('error', models.CharField(default='', max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LogicalModel')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=102400)),
                ('path', models.CharField(default=api.models.project.new_project_path, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedLogicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model)),
                ('bnd_file', models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model)),
                ('cfg_file', models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LogicalModel')),
            ],
        ),
        migrations.AddField(
            model_name='mabosssimulation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='logicalmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
