# Generated by Django 2.1.1 on 2018-09-05 14:09

import api.models.logical_model
import api.models.maboss
import api.models.project
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=api.models.logical_model.path_logical_model)),
            ],
        ),
        migrations.CreateModel(
            name='MaBoSSSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to=api.models.maboss.path_simulation_model)),
                ('fptable', models.CharField(max_length=102400, null=True)),
                ('nodes_probtraj', models.CharField(max_length=102400, null=True)),
                ('states_probtraj', models.CharField(max_length=102400, null=True)),
                ('fixpoints', models.CharField(max_length=102400, null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Interrupted', 'Interrupted'), ('Running', 'Busy'), ('Finished', 'Ended'), ('Failed', 'Error')], default='Queued', max_length=15)),
                ('error', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=102400)),
                ('path', models.CharField(default=api.models.project.new_project_path, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mabosssimulation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='logicalmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
