# Generated by Django 2.1.5 on 2019-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabossserver',
            name='desc',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
