# Generated by Django 2.1 on 2018-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaBoSSSimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fptable', models.CharField(max_length=102400, null=True)),
                ('nodes_probtraj', models.CharField(max_length=102400, null=True)),
                ('fixpoints', models.CharField(max_length=102400, null=True)),
            ],
        ),
    ]
