# Generated by Django 3.2.4 on 2021-06-14 13:00

import api.models.logical_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mabossserver_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='layout_file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model),
        ),
    ]
