# Generated by Django 2.1.3 on 2018-11-29 17:03

import api.models.maboss
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mabosssimulation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaBoSSSensitivityAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=12)),
                ('bnd_file', models.FileField(upload_to=api.models.maboss.path_sensitivityanalysis_model)),
                ('cfg_file', models.FileField(upload_to=api.models.maboss.path_sensitivityanalysis_model)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Interrupted', 'Interrupted'), ('Running', 'Busy'), ('Finished', 'Ended'), ('Failed', 'Error')], default='Queued', max_length=15)),
                ('error', models.CharField(default='', max_length=255, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LogicalModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MaBoSSSensitivitySimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fptable', models.TextField(null=True)),
                ('nodes_probtraj', models.TextField(null=True)),
                ('states_probtraj', models.TextField(null=True)),
                ('fixpoints', models.TextField(null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Interrupted', 'Interrupted'), ('Running', 'Busy'), ('Finished', 'Ended'), ('Failed', 'Error')], default='Queued', max_length=15)),
                ('error', models.CharField(default='', max_length=255, null=True)),
                ('sensitivity_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MaBoSSSensitivityAnalysis')),
            ],
        ),
    ]
