# Generated by Django 2.1 on 2018-08-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mabosssimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabosssimulation',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Interrupted', 'Interrupted'), ('Running', 'Busy'), ('Finished', 'Ended'), ('Failed', 'Error')], default='Queued', max_length=15),
        ),
    ]
