# Generated by Django 3.2.4 on 2021-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logicalmodel_layout_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabosssensitivityanalysis',
            name='nsimulations',
            field=models.IntegerField(default=0),
        ),
    ]
