# Generated by Django 2.1.2 on 2018-10-03 11:39

import api.models.logical_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mabossserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedLogicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to=api.models.logical_model.path_tagged_logical_model)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LogicalModel')),
            ],
        ),
    ]
