# Generated by Django 2.1 on 2018-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mabosssimulation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabosssimulation',
            name='error',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
