# Generated by Django 2.1 on 2018-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mabosssimulation_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabosssimulation',
            name='states_probtraj',
            field=models.CharField(max_length=102400, null=True),
        ),
    ]
