# Generated by Django 2.1 on 2018-08-29 14:07

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_mabosssimulation_states_probtraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logicalmodel',
            name='file',
            field=models.FileField(upload_to=api.models.path_logical_model),
        ),
    ]
