# Generated by Django 2.1.2 on 2018-10-24 14:59

import api.models.logical_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_logicalmodel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='bnd_file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model),
        ),
        migrations.AddField(
            model_name='logicalmodel',
            name='cfg_file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model),
        ),
        migrations.AlterField(
            model_name='logicalmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_logical_model),
        ),
    ]
