# Generated by Django 2.1.1 on 2018-09-04 09:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20180829_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=102400, null=True)),
                ('path', models.CharField(default=api.models.new_project_path, max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='logicalmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='mabosssimulation',
            name='model_file',
            field=models.FileField(default=None, upload_to=api.models.path_logical_model),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logicalmodel',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mabosssimulation',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
            preserve_default=False,
        ),
    ]
