# Generated by Django 2.1.2 on 2018-10-24 15:45

import api.models.logical_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181024_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedlogicalmodel',
            name='bnd_file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model),
        ),
        migrations.AddField(
            model_name='taggedlogicalmodel',
            name='cfg_file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model),
        ),
        migrations.AlterField(
            model_name='taggedlogicalmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=api.models.logical_model.path_tagged_logical_model),
        ),
    ]
