# Generated by Django 2.1.2 on 2018-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181024_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='format',
            field=models.CharField(choices=[('ZGinML', 'ZGinML'), ('MaBoSS', 'MaBoSS'), ('SBML', 'SBML')], default='ZGinML', max_length=10),
        ),
    ]
