# Generated by Django 2.1.2 on 2018-10-25 17:02

import api.models.maboss
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_logicalmodel_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mabosssimulation',
            old_name='model_file',
            new_name='bnd_file',
        ),
        migrations.AddField(
            model_name='mabosssimulation',
            name='cfg_file',
            field=models.FileField(default=None, upload_to=api.models.maboss.path_simulation_model),
            preserve_default=False,
        ),
    ]
