# Generated by Django 2.1.2 on 2018-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181025_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='mabosssimulation',
            name='path',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logicalmodel',
            name='path',
            field=models.CharField(max_length=12),
        ),
    ]
