# base image
#FROM cypress/browsers:chrome65-ff57
FROM cypress/base:8

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Install deps
RUN apt-get -qq update && apt-get install -y libatk-adaptor libgail-common libcanberra-gtk-module

# install cypress
RUN npm install cypress@2.1.0

# copy cypress files and folders
COPY frontend/cypress /usr/src/app/cypress
COPY frontend/cypress.json /usr/src/app/cypress.json

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify